apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan-microservice
  template:
    metadata:
      labels:
        app: loan-microservice
    spec:
      containers:
      - name: loan-microservice
        image: ghox19/loan-microservice:latest
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_DB_LOAN
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB_LOAN
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: loan-microservice
spec:
  selector:
    app: loan-microservice
  ports:
  - port: 8080
    targetPort: 8080