apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulation-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulation-microservice
  template:
    metadata:
      labels:
        app: simulation-microservice
    spec:
      containers:
      - name: simulation-microservice
        image: ghox19/simulation-microservice:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: simulation-microservice
spec:
  selector:
    app: simulation-microservice
  ports:
  - port: 80
    targetPort: 8080