apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulation-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulation-microservice
  template:
    metadata:
      labels:
        app: simulation-microservice
    spec:
      containers:
      - name: simulation-microservice
        image: ghox19/simulation-microservice:latest
        ports:
        - containerPort: 8080
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-server:8761/eureka/"
        - name: SPRING_APPLICATION_NAME
          value: "SIMULATION-MICROSERVICE"
        - name: SPRING_CLOUD_CONFIG_URI
          value: "http://config-server:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: simulation-microservice
spec:
  selector:
    app: simulation-microservice
  ports:
  - port: 80
    targetPort: 8080